version: '3.3'
services:
    web:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:fpm
        volumes:
            - ./src:/src